### ISSUE TITLE
Does not work in python 3.12 environments

### ISSUE THREAD

**Issue by ebourgeois** [dbrgn/coverage-badge#26]
```bash
Collecting coverage-badge
  Downloading coverage_badge-1.1.0-py2.py3-none-any.whl.metadata (3.2 kB)
Collecting coverage (from coverage-badge)
  Downloading coverage-7.4.4-cp312-cp312-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (8.2 kB)
Downloading coverage_badge-1.1.0-py2.py3-none-any.whl (6.4 kB)
Downloading coverage-7.4.4-cp312-cp312-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_17_x86_64.manylinux2014_x86_64.whl (238 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 238.2/238.2 kB 9.7 MB/s eta 0:00:00
Installing collected packages: coverage, coverage-badge
Successfully installed coverage-7.4.4 coverage-badge-1.1.0
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.12.2/x64/bin/coverage-badge", line 5, in <module>
    from coverage_badge.__main__ import main
  File "/opt/hostedtoolcache/Python/3.12.2/x64/lib/python3.12/site-packages/coverage_badge/__main__.py", line 7, in <module>
    import pkg_resources
ModuleNotFoundError: No module named 'pkg_resources'
```

`pkg_resources` is deprecated, please use `importlib`

**Comment by dbrgn** [comment]
A PR would be welcome!

**Comment by shaerpour** [comment]
I Successfully installed on Python 3.12.2

```bash
$ pip install coverage-badge
Collecting coverage-badge
  Using cached coverage_badge-1.1.0-py2.py3-none-any.whl.metadata (3.2 kB)
Collecting coverage (from coverage-badge)
  Using cached coverage-7.4.4-cp312-cp312-macosx_10_9_x86_64.whl.metadata (8.2 kB)
Using cached coverage_badge-1.1.0-py2.py3-none-any.whl (6.4 kB)
Using cached coverage-7.4.4-cp312-cp312-macosx_10_9_x86_64.whl (206 kB)
Installing collected packages: coverage, coverage-badge
Successfully installed coverage-7.4.4 coverage-badge-1.1.0
```

@ebourgeois

**Comment by dbrgn** [comment]
True, thanks for testing @shaerpour.

```
$ docker run --rm -ti python:3.12 /bin/bash
...
root@bdc38b43751f:/# pip install coverage-badge
Collecting coverage-badge
  Downloading coverage_badge-1.1.0-py2.py3-none-any.whl.metadata (3.2 kB)
Collecting coverage (from coverage-badge)
  Downloading coverage-7.4.4-cp312-cp312-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (8.2 kB)
Downloading coverage_badge-1.1.0-py2.py3-none-any.whl (6.4 kB)
Downloading coverage-7.4.4-cp312-cp312-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_17_x86_64.manylinux2014_x86_64.whl (238 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 238.2/238.2 kB 8.1 MB/s eta 0:00:00
Installing collected packages: coverage, coverage-badge
Successfully installed coverage-7.4.4 coverage-badge-1.1.0
```

**Comment by dbrgn** [comment]
More info: https://stackoverflow.com/questions/7446187/no-module-named-pkg-resources
