### ISSUE TITLE
Error with upgrade to package `coverage`

### ISSUE THREAD

**Issue by jessica-dyer** [dbrgn/coverage-badge#29]
I upgraded the package `coverage` from 7.4.4 to 7.5.0 and `coverage-badge` began to error.

When running `poetry run coverage-badge -o coverage.svg`, I get the following error: 

Traceback (most recent call last):
  ```
File "/Users/Repositories/polaris/.venv/bin/coverage-badge", line 8, in <module>
    sys.exit(main())
  File "/Users/Repositories/polaris/.venv/lib/python3.10/site-packages/coverage_badge/__main__.py", line 171, in main
    total = get_total()
  File "/Users/Repositories/polaris/.venv/lib/python3.10/site-packages/coverage_badge/__main__.py", line 76, in get_total
    return coverage.results.Numbers(precision=cov.config.precision).display_covered(total)
AttributeError: 'Numbers' object has no attribute 'display_covered'
```
I believe this is a bug in `coverage-badge` in relation to the newest version of `coverage`.

**Comment by mrgambal** [comment]
Can confirm: downgrading to `coverage==7.4.4` fixes the problem.

**Comment by jessica-dyer** [comment]
Thanks @mrgambal. I ended up reading the README and seeing that this package is in maintenance mode so this issue may not get fixed. Switched to `genbadge` as a replacement.

**Comment by mrgambal** [comment]
Yup, discovered the fact the same way :) Also I see there is a [PR](https://github.com/dbrgn/coverage-badge/pull/28) created that should fix this issue, yet it is still waiting for approval from @dbrgn.
Anyway, switching to `genbadge` sounds like a good idea.

p.s. Kudos to @dbrgn for the project anyway :)

**Comment by jessica-dyer** [comment]
Oh great! Thanks for linking that PR.

Yes, cool project @dbrgn! Thank you!

**Comment by dbrgn** [comment]
Thanks a lot @mrgambal and @jessica-dyer, that's appreciated!

**Comment by dbrgn** [comment]
Fix released in version 1.1.1. Nevertheless, migrating to another project like `genbadge` is likely a good idea 🙂
